spring:
  redis:
    database: 0
    host: localhost
    password: null
    port: 6379
    timeout: 3000
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huamall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:log4j.xml